name: Harsha AI Blogger

on:
  schedule:
    - cron: "27 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser huggingface_hub

      - name: Run blog generator
        run: python main.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "New Post" || exit 0
          git pull --rebase origin main
          git push
